# otter-browser
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/otter-browser.1.gz
complete -c otter-browser -l profile -d 'Specifies the directory that profile (user data) is kept in.  Defaults to ~/'
complete -c otter-browser -l cache -d 'Specifies the directory that cache data is kept in.  Defaults to ~/'
complete -c otter-browser -l session -d 'Tries to load session specified by IDENTIFIER'
complete -c otter-browser -l private-session -d 'Starts private session'
complete -c otter-browser -l session-chooser -d 'Forces session chooser dialog'
complete -c otter-browser -l portable -d 'Sets profile and cache paths to directories inside the same directory as that…'
complete -c otter-browser -l new-tab -d 'Loads URL in new tab'
complete -c otter-browser -l new-private-tab -d 'Loads URL in new private tab'
complete -c otter-browser -l new-window -d 'Loads URL in new window'
complete -c otter-browser -l new-private-window -d 'Loads URL in new private window'
complete -c otter-browser -l readonly -d 'Tells application to avoid writing data to disk'
complete -c otter-browser -l report -d 'Prints out diagnostic report and exits application'
complete -c otter-browser -s h -l help -d 'Show list of supported command line options'
complete -c otter-browser -s v -l version -d 'Show version information'

