# proot
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/proot.1.gz
complete -c proot -s r -l rootfs -d 'Use path as the new guest root file-system, default is /'
complete -c proot -s b -l bind -s m -l mount -d 'Make the content of path accessible in the guest rootfs'
complete -c proot -s q -l qemu -d 'Execute guest programs through QEMU as specified by command'
complete -c proot -s w -l pwd -l cwd -d 'Set the initial working directory to path'
complete -c proot -s v -l verbose -d 'Set the level of debug information to value'
complete -c proot -s V -l version -l about -d 'Print version, copyright, license and contact, then exit'
complete -c proot -s h -l help -l usage -d 'Print the version and the command-line usage, then exit'
complete -c proot -s k -l kernel-release -d 'Make current kernel appear as kernel release string'
complete -c proot -s 0 -l root-id -d 'Make current user appear as "root" and fake its privileges'
complete -c proot -s i -l change-id -d 'Make current user and group appear as string "uid:gid"'
complete -c proot -s R -d 'Alias: -r *path* + a couple of recommended -b'
complete -c proot -s S -d 'Alias: -0 -r *path* + a couple of recommended -b'
complete -c proot -o rw-r--r-- -d 'proot -b ~/alternate_hosts:/etc/hosts'

