# vncserver
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/vncserver.1.gz
complete -c vncserver -o name -d 'Each VNC desktop has a name which may be displayed by the viewer'
complete -c vncserver -o geometry -d 'Specify the size of the VNC desktop to be created.  Default is 1024x768'
complete -c vncserver -o depth -d 'Specify the pixel depth (in bits) of the VNC desktop to be created'
complete -c vncserver -o pixelformat -d 'Specify pixel format for Xvnc to use (BGRnnn or RGBnnn)'
complete -c vncserver -o cc -d 'As an alternative to the default TrueColor visual, this allows you to run an …'
complete -c vncserver -o kill -d 'This kills a VNC desktop previously started with vncserver'
complete -c vncserver -o fp -d 'If the vncserver script detects that the X Font Server (XFS) is running, it w…'
complete -c vncserver -o fg -d 'Runs Xvnc as a foreground process'
complete -c vncserver -o autokill -d 'Automatically kill Xvnc whenever the xstartup script exits'
complete -c vncserver -o noxstartup -d 'Do not run the %HOME/. vnc/xstartup script after launching Xvnc'
complete -c vncserver -o xstartup -d 'Run a custom startup script, instead of %HOME/'
complete -c vncserver -o list -d 'Lists all VNC desktops started by vncserver'

